from pathlib import Path


def replace_exact(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8").replace("\r\n", "\n")
    old = old.replace("\r\n", "\n")
    new = new.replace("\r\n", "\n")
    if old not in text:
        raise RuntimeError(f"Expected block not found in {path}: {old[:160]!r}")
    p.write_text(text.replace(old, new), encoding="utf-8", newline="\n")

# Correct open-role detection. SlotFlags and JobsPresent are parallel arrays; a slot
# is open when the corresponding JobsPresent entry is zero. Do not assume filled
# seats are packed at the front.
replace_exact(
    "LocalPfScanner.cs",
    '''            // Only inspect seats that are currently open. Filled seats and padding must not count toward role availability.\n            var openSlotCount = Math.Max(0, listing.SlotsAvailable - listing.SlotsFilled);\n            var acceptedJobs = listing.Slots\n                .Skip(listing.SlotsFilled)\n                .Take(openSlotCount)\n                .SelectMany(slot => slot.Accepting)\n                .Distinct()\n                .ToArray();''',
    '''            // SlotFlags and JobsPresent use the same seat indexes. A seat is open\n            // when JobsPresent[index] is 0; filled seats are not guaranteed to be\n            // packed at the front of the array.\n            var slots = listing.Slots.ToArray();\n            var jobsPresent = listing.RawJobsPresent.ToArray();\n            var seatCount = Math.Min((int)listing.SlotsAvailable, slots.Length);\n            var acceptedJobs = Enumerable.Range(0, seatCount)\n                .Where(index => index >= jobsPresent.Length || jobsPresent[index] == 0)\n                .SelectMany(index => slots[index].Accepting)\n                .Distinct()\n                .ToArray();''')

# Add rejection diagnostics.
replace_exact(
    "LocalPfScanner.cs",
    '''        var removedCount = 0;\n        var stateChanged = false;''',
    '''        var removedCount = 0;\n        var rejectionCounts = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);\n        var stateChanged = false;\n\n        void CountRejection(string reason)\n        {\n            rejectionCounts.TryGetValue(reason, out var count);\n            rejectionCounts[reason] = count + 1;\n        }''')

replace_exact(
    "LocalPfScanner.cs",
    '''            if (!listing.Duty.Contains(config.DutyNameContains.Trim(), StringComparison.OrdinalIgnoreCase))\n                continue;\n\n            var matches = MatchesLocalPfListing(listing, config);''',
    '''            if (!listing.Duty.Contains(config.DutyNameContains.Trim(), StringComparison.OrdinalIgnoreCase))\n            {\n                CountRejection("duty");\n                continue;\n            }\n\n            var rejectionReason = GetLocalPfRejectionReason(listing, config);\n            var matches = rejectionReason is null;\n            if (rejectionReason is not null)\n                CountRejection(rejectionReason);''')

replace_exact(
    "LocalPfScanner.cs",
    '''        LocalPfStatus =\n            $"Local PF: checked {DateTime.Now:t} - {listings.Count} High-End listings, " +\n            $"{matchingCount} matched, {newCount} new, {updatedCount} updated, {removedCount} removed ({completeness})";''',
    '''        var rejectionSummary = rejectionCounts.Count == 0\n            ? "none"\n            : string.Join(", ", rejectionCounts\n                .OrderBy(pair => pair.Key, StringComparer.OrdinalIgnoreCase)\n                .Select(pair => $"{pair.Key} {pair.Value}"));\n\n        LocalPfStatus =\n            $"Local PF: checked {DateTime.Now:t} - {listings.Count} High-End listings, " +\n            $"{matchingCount} matched, {newCount} new, {updatedCount} updated, {removedCount} removed; " +\n            $"rejected: {rejectionSummary} ({completeness})";''')

old_matcher = '''    private static bool MatchesLocalPfListing(LocalPfListingSnapshot listing, Configuration config)\n    {\n        if (!LocalPfNorthAmericanWorlds.Contains(listing.World))\n            return false;\n\n        if (listing.MinimumItemLevel == 999)\n            return false;\n\n        var openSlots = Math.Max(0, listing.TotalSlots - listing.FilledSlots);\n        if (openSlots < Math.Max(0, config.MinimumOpenSlots))\n            return false;\n\n        if (config.RequiredRole != RoleFilter.AnyRole &&\n            !listing.AcceptedJobs.Any(job => config.RequiredRole.Matches(job)))\n            return false;\n\n        return MatchesTextRules(listing.Duty, listing.Description, config);\n    }'''
new_matcher = '''    private static bool MatchesLocalPfListing(LocalPfListingSnapshot listing, Configuration config) =>\n        GetLocalPfRejectionReason(listing, config) is null;\n\n    private static string? GetLocalPfRejectionReason(LocalPfListingSnapshot listing, Configuration config)\n    {\n        if (!LocalPfNorthAmericanWorlds.Contains(listing.World))\n            return "world";\n\n        if (listing.MinimumItemLevel == 999)\n            return "iLvl 999";\n\n        var openSlots = Math.Max(0, listing.TotalSlots - listing.FilledSlots);\n        if (openSlots < Math.Max(0, config.MinimumOpenSlots))\n            return "open slots";\n\n        if (config.RequiredRole != RoleFilter.AnyRole &&\n            !listing.AcceptedJobs.Any(job => config.RequiredRole.Matches(job)))\n            return "role";\n\n        var haystack = listing.Duty + "\\n" + listing.Description;\n        var excludes = SplitKeywords(config.ExcludeKeywords);\n        if (excludes.Any(keyword => haystack.Contains(keyword, StringComparison.OrdinalIgnoreCase)))\n            return "excluded keyword";\n\n        var includes = SplitKeywords(config.IncludeKeywords);\n        if (includes.Length == 0)\n            return null;\n\n        var includeMatches = config.RequireAllIncludeKeywords\n            ? includes.All(keyword => haystack.Contains(keyword, StringComparison.OrdinalIgnoreCase))\n            : includes.Any(keyword => haystack.Contains(keyword, StringComparison.OrdinalIgnoreCase));\n\n        return includeMatches ? null : "include keyword";\n    }'''
replace_exact("LocalPfScanner.cs", old_matcher, new_matcher)

# Make party recruiter resolution robust when PartyLeaderIndex is temporarily invalid.
old_party = '''        var leaderIndex = PartyList.PartyLeaderIndex;\n        if (leaderIndex >= (uint)partySize)\n        {\n            UpdateCurrentPartyState(partyId, string.Empty, partySize, $"Current party: {partySize}/8 - waiting for leader data");\n            return;\n        }\n\n        var leader = PartyList[(int)leaderIndex];\n        if (leader is null)\n        {\n            UpdateCurrentPartyState(partyId != 0 ? partyId : 1, string.Empty, partySize, $"Current party: {partySize}/8 - waiting for leader data");\n            return;\n        }\n\n        var effectivePartyId = partyId != 0\n            ? partyId\n            : leader.ContentId != 0\n                ? unchecked((long)leader.ContentId)\n                : 1;\n\n        var leaderName = leader.Name.TextValue.Trim();\n        var leaderWorld = leader.World.Value.Name.ToString();\n        var recruiter = string.IsNullOrWhiteSpace(leaderWorld)\n            ? leaderName\n            : $"{leaderName} @ {leaderWorld}";\n\n        UpdateCurrentPartyState(\n            effectivePartyId,\n            recruiter,\n            partySize,\n            $"Current party: {partySize}/8 - highlighting matching PF card");'''
new_party = '''        var leaderIndex = PartyList.PartyLeaderIndex;\n        var identities = new List<(string Identity, ulong ContentId, bool IsLeader)>();\n\n        for (var i = 0; i < partySize; i++)\n        {\n            var member = PartyList[i];\n            if (member is null)\n                continue;\n\n            var name = member.Name.TextValue.Trim();\n            if (string.IsNullOrWhiteSpace(name))\n                continue;\n\n            var world = member.World.Value.Name.ToString();\n            var identity = string.IsNullOrWhiteSpace(world)\n                ? name\n                : $"{name} @ {world}";\n            identities.Add((identity, member.ContentId, (uint)i == leaderIndex));\n        }\n\n        var leaderIdentity = identities.FirstOrDefault(x => x.IsLeader);\n        var recruiter = leaderIdentity.Identity ?? string.Empty;\n\n        // Cross-world PF transitions can temporarily leave PartyLeaderIndex invalid.\n        // In that case, identify the recruiter by matching every current party member\n        // against the PF cards PartyPing is already tracking.\n        if (string.IsNullOrWhiteSpace(recruiter) ||\n            !activePfAlerts.Keys.Any(key => FingerprintRecruiterEquals(key, recruiter)))\n        {\n            var matchedIdentity = identities\n                .Select(x => x.Identity)\n                .FirstOrDefault(identity => activePfAlerts.Keys.Any(key =>\n                    FingerprintRecruiterEquals(key, identity) &&\n                    FingerprintMatchesConfiguredDuty(key, Configuration.DutyNameContains)));\n\n            if (!string.IsNullOrWhiteSpace(matchedIdentity))\n                recruiter = matchedIdentity;\n        }\n\n        var fallbackContentId = identities.FirstOrDefault(x => x.IsLeader).ContentId;\n        if (fallbackContentId == 0 && identities.Count > 0)\n            fallbackContentId = identities[0].ContentId;\n\n        var effectivePartyId = partyId != 0\n            ? partyId\n            : fallbackContentId != 0\n                ? unchecked((long)fallbackContentId)\n                : 1;\n\n        UpdateCurrentPartyState(\n            effectivePartyId,\n            recruiter,\n            partySize,\n            string.IsNullOrWhiteSpace(recruiter)\n                ? $"Current party: {partySize}/8 - detected; waiting to identify PF recruiter"\n                : $"Current party: {partySize}/8 - highlighting matching PF card");'''
replace_exact("PartyTracker.cs", old_party, new_party)

Path("version.txt").write_text("0.7.9.0\n", encoding="utf-8", newline="\n")
