from pathlib import Path


def rep(path, old, new):
    p = Path(path)
    text = p.read_text(encoding='utf-8').replace('\r\n', '\n')
    if old not in text:
        raise RuntimeError(f'Expected block not found in {path}: {old[:120]!r}')
    p.write_text(text.replace(old, new), encoding='utf-8', newline='\n')

# Stop the obsolete one-shot party tracker from overwriting the new current-party state.
rep('Plugin.cs', '''        try\n        {\n            TrackPartyFill();\n        }\n        catch (Exception ex)\n        {\n            PartyFillStatus = "Party fill tracker error: " + ex.Message;\n            Log.Warning(ex, "PartyPing party fill tracker error");\n        }\n''', '')

# Normalize Unicode and whitespace before keyword matching. This catches full-width
# letters/numbers and inconsistent spacing without changing ANY/ALL semantics.
rep('Plugin.cs', 'using Dalamud.Game.ClientState.Conditions;\n', 'using System.Text;\nusing Dalamud.Game.ClientState.Conditions;\n')
rep('Plugin.cs', '''    private static bool MatchesTextRules(string dutyName, string description, Configuration config)\n    {\n        var haystack = dutyName + "\\n" + description;\n        var includes = SplitKeywords(config.IncludeKeywords);\n        var excludes = SplitKeywords(config.ExcludeKeywords);\n\n        if (excludes.Any(k => haystack.Contains(k, StringComparison.OrdinalIgnoreCase)))\n            return false;\n\n        if (includes.Length == 0)\n            return true;\n\n        return config.RequireAllIncludeKeywords\n            ? includes.All(k => haystack.Contains(k, StringComparison.OrdinalIgnoreCase))\n            : includes.Any(k => haystack.Contains(k, StringComparison.OrdinalIgnoreCase));\n    }\n\n    private static string[] SplitKeywords(string raw) => raw\n        .Split([',', ';', '\\n', '\\r'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)\n        .Where(x => x.Length > 0)\n        .Distinct(StringComparer.OrdinalIgnoreCase)\n        .ToArray();\n''', '''    private static bool MatchesTextRules(string dutyName, string description, Configuration config)\n    {\n        var haystack = NormalizeMatchText(dutyName + "\\n" + description);\n        var includes = SplitKeywords(config.IncludeKeywords);\n        var excludes = SplitKeywords(config.ExcludeKeywords);\n\n        if (excludes.Any(k => haystack.Contains(k, StringComparison.OrdinalIgnoreCase)))\n            return false;\n\n        if (includes.Length == 0)\n            return true;\n\n        return config.RequireAllIncludeKeywords\n            ? includes.All(k => haystack.Contains(k, StringComparison.OrdinalIgnoreCase))\n            : includes.Any(k => haystack.Contains(k, StringComparison.OrdinalIgnoreCase));\n    }\n\n    private static string[] SplitKeywords(string raw) => NormalizeMatchText(raw)\n        .Split([',', ';', '\\n', '\\r'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)\n        .Select(NormalizeMatchText)\n        .Where(x => x.Length > 0)\n        .Distinct(StringComparer.OrdinalIgnoreCase)\n        .ToArray();\n\n    private static string NormalizeMatchText(string value)\n    {\n        if (string.IsNullOrWhiteSpace(value))\n            return string.Empty;\n\n        var normalized = value.Normalize(NormalizationForm.FormKC);\n        var builder = new StringBuilder(normalized.Length);\n        var pendingSpace = false;\n\n        foreach (var ch in normalized)\n        {\n            if (char.IsWhiteSpace(ch))\n            {\n                pendingSpace = builder.Length > 0;\n                continue;\n            }\n\n            if (pendingSpace)\n            {\n                builder.Append(' ');\n                pendingSpace = false;\n            }\n\n            builder.Append(ch);\n        }\n\n        return builder.ToString();\n    }\n''')

# A valid party is indicated by the live member count. PartyId can be zero during
# states where the party list is still populated, so use a fallback identity instead.
rep('PartyTracker.cs', '''        if (partySize <= 1 || partyId == 0)\n        {\n            UpdateCurrentPartyState(0, string.Empty, 0, "Current party: not in a party");\n            return;\n        }\n''', '''        if (partySize <= 1)\n        {\n            UpdateCurrentPartyState(0, string.Empty, 0, "Current party: not in a party");\n            return;\n        }\n''')
rep('PartyTracker.cs', '''        var leader = PartyList[(int)leaderIndex];\n        if (leader is null)\n        {\n            UpdateCurrentPartyState(partyId, string.Empty, partySize, $"Current party: {partySize}/8 - waiting for leader data");\n            return;\n        }\n\n        var leaderName = leader.Name.TextValue.Trim();''', '''        var leader = PartyList[(int)leaderIndex];\n        if (leader is null)\n        {\n            UpdateCurrentPartyState(partyId != 0 ? partyId : 1, string.Empty, partySize, $"Current party: {partySize}/8 - waiting for leader data");\n            return;\n        }\n\n        var effectivePartyId = partyId != 0\n            ? partyId\n            : leader.ContentId != 0\n                ? unchecked((long)leader.ContentId)\n                : 1;\n\n        var leaderName = leader.Name.TextValue.Trim();''')
rep('PartyTracker.cs', '''        UpdateCurrentPartyState(\n            partyId,\n            recruiter,''', '''        UpdateCurrentPartyState(\n            effectivePartyId,\n            recruiter,''')
rep('PartyTracker.cs', '''            return currentPartyId != 0 &&\n                   currentPartySize > 1 &&''', '''            return currentPartySize > 1 &&''')
rep('PartyTracker.cs', '''        lock (currentPartySync)\n            return currentPartyId != 0 && currentPartySize > 1;''', '''        lock (currentPartySync)\n            return currentPartySize > 1;''')
rep('PartyTracker.cs', '''            else if (partyId != 0)\n            {\n                PartyFillStatus = $"Current party: {partySize}/8 - waiting for matching PF card";\n            }''', '''            else if (partySize > 1)\n            {\n                PartyFillStatus = $"Current party: {partySize}/8 - waiting for matching PF card";\n            }''')
rep('PartyTracker.cs', '''            if (partyId == 0 &&\n                Configuration.Enabled &&''', '''            if (partySize <= 1 &&\n                Configuration.Enabled &&''')

# Replace the fixed 2.5-second capture with a quiet-period listener so slow/bursty
# ReceiveListing streams are not cut off early.
rep('LocalPfScanner.cs', '''    private static readonly TimeSpan LocalPfReceiveWindow = TimeSpan.FromMilliseconds(2500);\n''', '''    private static readonly TimeSpan LocalPfMaximumReceiveWindow = TimeSpan.FromSeconds(5);\n    private static readonly TimeSpan LocalPfMinimumReceiveWindow = TimeSpan.FromMilliseconds(1500);\n    private static readonly TimeSpan LocalPfQuietPeriod = TimeSpan.FromMilliseconds(900);\n''')
rep('LocalPfScanner.cs', '''    private readonly object localPfSync = new();\n    private readonly Dictionary<ulong, LocalPfListingSnapshot> localPfReceived = new();\n''', '''    private readonly object localPfSync = new();\n    private readonly Dictionary<ulong, LocalPfListingSnapshot> localPfReceived = new();\n    private DateTime localPfLastReceiveUtc = DateTime.MinValue;\n''')
rep('LocalPfScanner.cs', '''        lock (localPfSync)\n            localPfReceived.Clear();\n''', '''        lock (localPfSync)\n        {\n            localPfReceived.Clear();\n            localPfLastReceiveUtc = DateTime.MinValue;\n        }\n''')
rep('LocalPfScanner.cs', '''            await Task.Delay(LocalPfReceiveWindow, cancellation.Token).ConfigureAwait(false);\n\n            LocalPfListingSnapshot[] listings;\n''', '''            await WaitForLocalPfResponseAsync(cancellation.Token).ConfigureAwait(false);\n\n            LocalPfListingSnapshot[] listings;\n''')
rep('LocalPfScanner.cs', '''            lock (localPfSync)\n                localPfReceived[listing.Id] = snapshot;\n''', '''            lock (localPfSync)\n            {\n                localPfReceived[listing.Id] = snapshot;\n                localPfLastReceiveUtc = DateTime.UtcNow;\n            }\n''')
insert_before = '''    private async Task ProcessLocalPfResultsAsync(\n'''
helper = '''    private async Task WaitForLocalPfResponseAsync(CancellationToken cancellationToken)\n    {\n        var startedUtc = DateTime.UtcNow;\n\n        while (DateTime.UtcNow - startedUtc < LocalPfMaximumReceiveWindow)\n        {\n            await Task.Delay(100, cancellationToken).ConfigureAwait(false);\n\n            int count;\n            DateTime lastReceiveUtc;\n            lock (localPfSync)\n            {\n                count = localPfReceived.Count;\n                lastReceiveUtc = localPfLastReceiveUtc;\n            }\n\n            if (count >= LocalPfMaxListingsPerPage)\n                return;\n\n            var elapsed = DateTime.UtcNow - startedUtc;\n            if (count > 0 &&\n                elapsed >= LocalPfMinimumReceiveWindow &&\n                DateTime.UtcNow - lastReceiveUtc >= LocalPfQuietPeriod)\n            {\n                return;\n            }\n        }\n    }\n\n'''
rep('LocalPfScanner.cs', insert_before, helper + insert_before)

Path('version.txt').write_text('0.7.8.0\n', encoding='utf-8', newline='\n')
